### ISSUE TITLE
How can we add like a Pod?

### ISSUE THREAD

**Issue by vishaldeshai** [SahebRoy92/SRPopView#2]
Hello,

Can we add SRPopView using pod?

thanks in advance.
Vishal

**Comment by SahebRoy92** [comment]
Yes I am working on a swift version also with some enhancement, will update to a pod in a few days

**Comment by SahebRoy92** [comment]
Pod version is available

**Comment by vishaldeshai** [comment]
Ok thanks

**Comment by SahebRoy92** [comment]
I am adding to the trunk pod so it might take a few hours to take effect, so watch out for the update here

**Comment by vishaldeshai** [comment]
sure.
