### ISSUE TITLE
Touchable issue

### ISSUE THREAD

**Issue by vishaldeshai** [SahebRoy92/SRPopView#4]
Hello,

Sometimes it is proper sensible like when tap on near by search field it is hide.

thanks in advance.

**Comment by SahebRoy92** [comment]
Can you explain the issue again? I am working on the swift version along with cocoapod support, so I will fix this if this issue remains

**Comment by vishaldeshai** [comment]
Scenario
set Auto Search Yes and number of records are 29.

i touch left of search textfield(10-15 pixel space) or right of search textfield(10-15 pixel space) and popup gone.

it may be raise issue around search textfield like top,bottom,left,right.

if you run on device then you can more familier with touch issues.

**Comment by SahebRoy92** [comment]
Ok got it, as i said i am coming up with a new version and hopefully by this week I can solve this issue as well. As always feedback is always appreciated

**Comment by vishaldeshai** [comment]
Resolved.

`-(void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event{
    if([touches anyObject].view != self.tblSuperView){
        if([touches anyObject].view == _searchView){
            NSLog(@"UITextField Tapped");
        }else if(!isKeyboardUp){
            [self dismissView];
            [self.delegate didRemoveSelfWithoutPicking];
        }
        else {
            isKeyboardUp = NO;
            [self endEditing:YES];
        }
    }
}
`

**Comment by SahebRoy92** [comment]
closing the issue then
