### ISSUE TITLE
Update Values

### ISSUE THREAD

**Issue by vishaldeshai** [SahebRoy92/SRPopView#5]
Hello,

i have to update values of SRPopView's items array when popup appears on screen.

i can reload using following statement:
[SRPopView reloadValues];
 but i need to change my array and then reload is it possible?

thanks in advance

**Comment by SahebRoy92** [comment]
Fixed! - call `SRPopView.shared.reloadDataWithUpdatedValues(_ updatedInputValues : [String]` method to reload data while popview is on screen.

P.S - Please download latest code through cocoapods
